### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by ash-grennan** [staff0rd/tfx-cloudflare-purge#1]
What's the cause of this error? The credentials and domain are correct.

Starting: Purge Cloudflare cache
==============================================================================
Task         : Purge Cache for Cloudflare
Description  : Purge files from a Cloudflare cache
Version      : 1.1.556
Author       : Stafford Williams
Help         : 
==============================================================================
[error]Unhandled: Cannot read property 'id' of undefined
Finishing: Purge Cloudflare cache

Thanks

**Comment by staff0rd** [comment]
Looks like the only reference to `id` is [here](https://github.com/staff0rd/tfx-cloudflare-purge/blob/f876e6e9807763cf4a8d7738feb3f10ba2a632c3/cloudflarePurge/index.ts#L26), which inspects the response from a call to [this endpoint](https://api.cloudflare.com/#zone-list-zones).

Likely your zone name is either wrong or inactive?

I'll update the code to check for this.
